#NTC.BPD_M GSEA term list
keylist <- list()
#smoothed reactome
keylist[["smoothed"]][["Reactome"]] = list(keywords = c("GPCR","Respiratory","Translation","Interleukin"),
                                           decidedterms = list(c("GPCR Ligand Binding R-HSA-500792","GPCR Downstream Signaling R-HSA-388396"),
                                                               c("Respiratory Electron Transport R-HSA-611105"),
                                                               c("Mitochondrial Translation R-HSA-5368287",
                                                                 "Metabolism Of Amino Acids And Derivatives R-HSA-71291"),
                                                               c("Cytokine Signaling In Immune System R-HSA-1280215")),
                                           extra.terms = c("Platelet Degranulation R-HSA-114608",
                                                           "FOXO-mediated Transcription Of Cell Cycle Genes R-HSA-9617828",
                                                           "Complement Cascade R-HSA-166658"))
#smoothed GO BP
keylist[["smoothed"]][["GO-BP"]] = list(keywords= c("Mitochondrial","Differentiation",
                                                    "Antigen","Microglia",
                                                    "Chemo","Tumor"),
                                        decidedterms = list(c("Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)",
                                                              "Mitochondrial Translation (GO:0032543)",
                                                              "Mitochondrial Respiratory Chain Complex Assembly (GO:0033108)"),
                                                            c("Regulation of Epithelial Cell Differentiation (GO:0030856)"),
                                                            c("Positive Regulation of Immune Response (GO:0050778)"),
                                                            c("Microglial Cell Activation (GO:0001774)"),
                                                            c("Regulation of Chemokine Production (GO:0032642)",
                                                              "Positive Regulation of Cytokine Production (GO:0001819)"),
                                                            c("Cellular Response to Tumor Necrosis Factor (GO:0071356)")),
                                        extra.terms = c("Positive Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042531)",
                                                        "Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167)",
                                                        "Positive Regulation of Viral Entry Into Host Cell (GO:0046598)",
                                                        "Positive Regulation by Symbiont of Entry Into Host (GO:0075294)",
                                                        "Positive Regulation of Lymphocyte Proliferation (GO:0050671)",
                                                        "Visual System Development (GO:0150063)",
                                                        "Cellular Response to Low-Density Lipoprotein Particle Stimulus (GO:0071404)",
                                                        "+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897)",
                                                        "Leukocyte Tethering or Rolling (GO:0050901)",
                                                        "Cellular Response to Transforming Growth Factor Beta Stimulus (GO:0071560)",
                                                        "Positive Regulation of Phagocytosis (GO:0050766)",
                                                        "Positive Regulation of Endocytosis (GO:0045807)",
                                                        "Receptor Clustering (GO:0043113)",
                                                        "Non-Canonical NF-kappaB Signal Transduction (GO:0038061)",
                                                        "3'-UTR-mediated mRNA Stabilization (GO:0070935)",
                                                        "Regulation of mRNA Catabolic Process (GO:0061013)"))
#smoothed GO CC
keylist[["smoothed"]][["GO-CC"]]= list(keywords= c("Vesicle Membrane"),
                                       decidedterms = list(c("Coated Vesicle Membrane (GO:0030662)",
                                                             "Clathrin-Coated Vesicle Membrane (GO:0030665)")),
                                       extra.terms = c("Platelet Alpha Granule Lumen (GO:0031093)",
                                                       "Tertiary Granule Membrane (GO:0070821)",
                                                       "Tertiary Granule (GO:0070820)",
                                                       "Extracellular Vesicle (GO:1903561)",
                                                       "Extracellular Membrane-Bounded Organelle (GO:0065010)"))
#seurat reactome
keylist[["seurat"]][["Reactome"]] = list(keywords = c("GPCR","Citric Acid","Translation","Complement","Interleukin"),
                                         decidedterms = list(c("GPCR Ligand Binding R-HSA-500792","GPCR Downstream Signaling R-HSA-388396"),
                                                             c("Respiratory Electron Transport R-HSA-611105"),
                                                             c("Translation R-HSA-72766"),
                                                             c("Complement Cascade R-HSA-166658"),
                                                             c("Cytokine Signaling In Immune System R-HSA-1280215")),
                                         extra.terms = c("Platelet Degranulation R-HSA-114608"))
#seurat GO BP
keylist[["seurat"]][["GO-BP"]] = list(keywords= c("Mitochondrial","Stimulus","Antigen","Chemo","Microglia","Tumor"),
                                      decidedterms = list(c("Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)",
                                                            "Mitochondrial Respiratory Chain Complex Assembly (GO:0033108)"),
                                                          c("Cellular Response to Growth Factor Stimulus (GO:0071363)",
                                                            "Positive Regulation of Immune Response (GO:0050778)"),
                                                          c("Peptide Antigen Assembly With MHC Protein Complex (GO:0002501)",
                                                            "Positive Regulation of Immune Response (GO:0050778)"),
                                                          c("Regulation of Chemokine Production (GO:0032642)",
                                                            "Positive Regulation of Chemotaxis (GO:0050921)"),
                                                          c("Microglial Cell Activation (GO:0001774)"),
                                                          c("Cytokine-Mediated Signaling Pathway (GO:0019221)",
                                                            "Response to Tumor Necrosis Factor (GO:0034612)")),
                                      extra.terms = c("Leukocyte Tethering or Rolling (GO:0050901)",
                                                      "Negative Regulation of Leukocyte Mediated Cytotoxicity (GO:0001911)",
                                                      "Positive Regulation of Mononuclear Cell Migration (GO:0071677)",
                                                      "Regulation of Phagocytosis (GO:0050764)",
                                                      "3'-UTR-mediated mRNA Stabilization (GO:0070935)"))
#seurat GO CC
keylist[["seurat"]][["GO-CC"]] = list(
  keywords= c("Vesicle Membrane"),
  decidedterms = list(c("Phagocytic Vesicle (GO:0045335)",
                        "Coated Vesicle Membrane (GO:0030662)",
                        "Clathrin-Coated Vesicle Membrane (GO:0030665)")),
  extra.terms = c("Tertiary Granule (GO:0070820)",
                  "Tertiary Granule Membrane (GO:0070821)",
                  "Platelet Alpha Granule Lumen (GO:0031093)")
)
